
exports.seed = function(knex, Promise) {
  return knex('pups').del()
    .then(function () {
      return Promise.all([
        knex('pups').insert({id: 1,
          user_id: '1',
          breed: 'Bull Terrier',
          size: 'Medium',
          temperament: 'Playful',
          neutered: true,
          age: '1',
          avatar_url: '/styles/pictures/bull.jpg',
          name: 'Tucker',
          sex: 'male'
        }),
        knex('pups').insert({id: 2,
          user_id: '1',
          breed: 'Boston Terrier',
          size: 'Small',
          temperament: 'Energetic',
          neutered: true,
          age: '3',
          avatar_url: '/styles/pictures/boston.jpg',
          name: 'Brodie',
          sex: 'male'
        }),
        knex('pups').insert({id: 3,
          user_id: '2',
          breed: 'Husky',
          size: 'Medium-Large',
          temperament: 'Cheerful',
          neutered: true,
          age: '5',
          avatar_url:'/styles/pictures/husky.jpg',
          name: 'Molly',
          sex: 'female'
        }),
        knex('pups').insert({id: 4,
          user_id: '3',
          breed: 'Long-haired Mini Daschund',
          size: 'Small',
          temperament: 'Friendly',
          neutered: true,
          age: '1',
          avatar_url:'/styles/pictures/mini.jpg',
          name: 'Joey',
          sex: 'male'
        }),
          knex('pups').insert({id: 4,
          user_id: '3',
          breed: 'Long-haired Mini Daschund',
          size: 'Small',
          temperament: 'Playful',
          neutered: true,
          age: '1',
          avatar_url:'/styles/pictures/mini2.jpg',
          name: 'Penny',
          sex: 'female'
        }),
        knex('pups').insert({id: 5,
          user_id: '3',
          breed: 'Golden Retriever',
          size: 'Medium',
          temperament: 'Active',
          neutered: true,
          age: '1',
          avatar_url:'/styles/pictures/golden.jpg',
          name: 'Charlie',
          sex: 'male'
        }),
         knex('pups').insert({id: 6,
          user_id: '4',
          breed: 'Husky Pomeranian',
          size: 'Small',
          temperament: 'Active',
          neutered: true,
          age: '1',
          avatar_url:'/styles/pictures/huksypom.jpg',
          name: 'Baxter',
          sex: 'male'
        }),
          knex('pups').insert({id: 7,
          user_id: '4',
          breed: 'Pomeranian',
          size: 'Small',
          temperament: 'Quiet',
          neutered: true,
          age: '2',
          avatar_url:'/styles/pictures/pom.jpg',
          name: 'Fiona',
          sex: 'female'
        }),
          knex('pups').insert({id: 8,
          user_id: '5',
          breed: 'German Shepherd',
          size: 'Large',
          temperament: 'Active',
          neutered: true,
          age: '4',
          avatar_url:'/styles/pictures/german.jpg',
          name: 'Jessi',
          sex: 'female'
        }),
          knex('pups').insert({id: 9,
          user_id: '6',
          breed: 'Border Collie',
          size: 'Medium',
          temperament: 'Quiet',
          neutered: true,
          age: '2',
          avatar_url:'/styles/pictures/collie.jpg',
          name: 'Calli',
          sex: 'female'
        }),
          knex('pups').insert({id: 10,
          user_id: '6',
          breed: 'Blue Heeler',
          size: 'Small',
          temperament: 'Playful',
          neutered: true,
          age: '1',
          avatar_url:'/styles/pictures/heeler.jpg',
          name: 'Timmy',
          sex: 'male'
        }),
          knex('pups').insert({id: 11,
          user_id: '7',
          breed: 'Chow Chow',
          size: 'Medium',
          temperament: 'Assertive',
          neutered: true,
          age: '3',
          avatar_url:'/styles/pictures/chow.jpg',
          name: 'Ace',
          sex: 'male'
        }),
          knex('pups').insert({id: 12,
          user_id: '8',
          breed: 'St.Bernard',
          size: 'Large',
          temperament: 'Calm',
          neutered: true,
          age: '6',
          avatar_url:'/styles/pictures/bernard.jpg',
          name: 'Brock',
          sex: 'male'
        }),
          knex('pups').insert({id: 13,
          user_id: '8',
          breed: 'Great Dane',
          size: 'Large',
          temperament: 'Quiet',
          neutered: true,
          age: '5',
          avatar_url:'/styles/pictures/dane.jpg',
          name: 'Sasha',
          sex: 'female'
        }),
          knex('pups').insert({id: 14,
          user_id: '9',
          breed: 'Chihuahua',
          size: 'Small',
          temperament: 'Energetic',
          neutered: true,
          age: '4',
          avatar_url:'/styles/pictures/chi.jpg',
          name: 'Finley',
          sex: 'male'
        }),
          knex('pups').insert({id: 15,
          user_id: '9',
          breed: 'Long Haired Chihuahua',
          size: 'Small',
          temperament: 'Friendly',
          neutered: true,
          age: '3',
          avatar_url:'/styles/pictures/chi2.jpg',
          name: 'Betsy',
          sex: 'female'
        }),
          knex('pups').insert({id: 16,
          user_id: '10',
          breed: 'Labradoodle',
          size: 'Medium',
          temperament: 'Energetic',
          neutered: true,
          age: '3',
          avatar_url:'/styles/pictures/labradoodle.jpg',
          name: 'Chester',
          sex: 'male'
        }),
          knex('pups').insert({id: 17,
          user_id: '11',
          breed: 'Chinese Crested',
          size: 'Small',
          temperament: 'Playful',
          neutered: true,
          age: '5',
          avatar_url:'/styles/pictures/crested.jpg',
          name: 'Parker',
          sex: 'male'
        }),
      ]);
    });
};
